name: mattermost-desktop
version: 3.7.1
summary: Open source, private cloud Slack-alternative
description: |
  Mattermost is secure workplace messaging from behind your firewall.

  - Discuss topics in private groups, one-to-one or team-wide
  - Easily share and view image files
  - Connect in-house systems with webhooks and Slack-compatible integrations

  To use this app, you need a URL for a Mattermost server.

  -------

  Host your own server: https://about.mattermost.com/download

  Terms of Service: http://about.mattermost.com/terms/

  Contribute to the project: https://github.com/mattermost/desktop
grade: stable
confinement: strict
# Point the following path to the original icons directory if/when this gets merged
# with the mattermost desktop repo.
icon: mattermost-desktop.png
parts:
  mattermost-desktop:
    plugin: dump
    source: https://releases.mattermost.com/desktop/3.7.1/mattermost-desktop-3.7.1-linux-amd64.deb
    source-type: deb
    # Correct path to icon.
    prepare: |
      sed -i 's|Icon=mattermost-desktop|Icon=\${SNAP}/meta/gui/icon.png|' usr/share/applications/mattermost-desktop.desktop
    after:
      - desktop-gtk2
    stage-packages:
      - libasound2
      - libgconf2-4
      - libnotify4
      - libnspr4
      - libnss3
      - libpulse0
      - libxss1
      - libxtst6

apps:
  mattermost-desktop:
    command: bin/desktop-launch $SNAP/opt/Mattermost/mattermost-desktop
    desktop: usr/share/applications/mattermost-desktop.desktop
    # Correct the TMPDIR path for Chromium Framework/Electron to ensure
    # libappindicator has readable resources.
    environment:
      TMPDIR: $XDG_RUNTIME_DIR
    plugs:
      - bluez
      - browser-support
      - gsettings
      - home
      - mount-observe
      - network
      - network-bind
      - opengl
      - pulseaudio
      - unity7
      - wayland
      - x11
